package com.work.challengeyapeapp.core.mapsUtils

const val AMERICAN_LATITUDE = 38.9072
const val AMERICAN_LONGITUDE = -77.0369
const val BRITISH_LATITUDE = 51.5074
const val BRITISH_LONGITUDE = -0.1278
const val CANADIAN_LATITUDE = 45.4215
const val CANADIAN_LONGITUDE = -75.6972
const val CHINESE_LATITUDE = 39.9042
const val CHINESE_LONGITUDE = 116.4074
const val CROATIAN_LATITUDE = 45.8150
const val CROATIAN_LONGITUDE = 15.9819
const val DUTCH_LATITUDE = 52.3676
const val DUTCH_LONGITUDE = 4.9041
const val EGYPTIAN_LATITUDE = 30.0444
const val EGYPTIAN_LONGITUDE = 31.2357
const val FRENCH_LATITUDE = 48.8566
const val FRENCH_LONGITUDE = 2.3522
const val GREEK_LATITUDE = 37.9838
const val GREEK_LONGITUDE = 23.7275
const val INDIAN_LATITUDE = 28.6139
const val INDIAN_LONGITUDE = 77.2090
const val IRISH_LATITUDE = 53.3498
const val IRISH_LONGITUDE = -6.2603
const val ITALIAN_LATITUDE = 41.9028
const val ITALIAN_LONGITUDE = 12.4964
const val JAPANESE_LATITUDE = 35.6895
const val JAPANESE_LONGITUDE = 139.6917
const val MEXICAN_LATITUDE = 19.4326
const val MEXICAN_LONGITUDE = -99.1332
const val RUSSIAN_LATITUDE = 55.7558
const val RUSSIAN_LONGITUDE = 37.6173
const val SPANISH_LATITUDE = 40.4168
const val SPANISH_LONGITUDE = -3.7038
const val TURKISH_LATITUDE = 39.9334
const val TURKISH_LONGITUDE = 32.8597
const val VIETNAMESE_LATITUDE = 21.0285
const val VIETNAMESE_LONGITUDE = 105.8542
const val AUSTRALIAN_LATITUDE = -35.2809
const val AUSTRALIAN_LONGITUDE = 149.1300
const val BRAZILIAN_LATITUDE = -15.8267
const val BRAZILIAN_LONGITUDE = -47.9218
const val GERMAN_LATITUDE = 52.5200
const val GERMAN_LONGITUDE = 13.4050
const val KOREAN_LATITUDE = 37.5665
const val KOREAN_LONGITUDE = 126.9780
const val SWEDISH_LATITUDE = 59.3293
const val SWEDISH_LONGITUDE = 18.0686
const val SWISS_LATITUDE = 46.9481
const val SWISS_LONGITUDE = 7.4474
const val THAI_LATITUDE = 13.7563
const val THAI_LONGITUDE = 100.5018
const val BELGIAN_LATITUDE = 50.8503
const val BELGIAN_LONGITUDE = 4.3517
const val AUSTRIAN_LATITUDE = 48.2082
const val AUSTRIAN_LONGITUDE = 16.3738
const val DANISH_LATITUDE = 55.6761
const val DANISH_LONGITUDE = 12.5683
const val PORTUGUESE_LATITUDE = 38.7223
const val PORTUGUESE_LONGITUDE = -9.1393
const val POLISH_LATITUDE = 52.2297
const val POLISH_LONGITUDE = 21.0122
const val HUNGARIAN_LATITUDE = 47.4979
const val HUNGARIAN_LONGITUDE = 19.0402
const val MOROCCAN_LATITUDE = 33.9716
const val MOROCCAN_LONGITUDE = -6.8498
const val TUNISIAN_LATITUDE = 36.8065
const val TUNISIAN_LONGITUDE = 10.1815
const val FILIPINO_LATITUDE = 14.5995
const val FILIPINO_LONGITUDE = 120.9842
const val KENYAN_LATITUDE = -1.2864
const val KENYAN_LONGITUDE = 36.8172
const val MALAYSIAN_LATITUDE = 3.1390
const val MALAYSIAN_LONGITUDE = 101.6869
const val JAMAICAN_LATITUDE = 18.0179
const val JAMAICAN_LONGITUDE = -76.8099
const val UNKNOWN_LATITUDE = 37.0000
const val UNKNOWN_LONGITUDE = -95.0000

enum class Gentiles (val coordinates: Pair<Double, Double>){
    American (AMERICAN_LATITUDE to AMERICAN_LONGITUDE),
    British (BRITISH_LATITUDE to BRITISH_LONGITUDE),
    Canadian (CANADIAN_LATITUDE to CANADIAN_LONGITUDE),
    Chinese (CHINESE_LATITUDE to CHINESE_LONGITUDE),
    Croatian (CROATIAN_LATITUDE to CROATIAN_LONGITUDE),
    Dutch (DUTCH_LATITUDE to DUTCH_LONGITUDE),
    Egyptian (EGYPTIAN_LATITUDE to EGYPTIAN_LONGITUDE),
    French (FRENCH_LATITUDE to FRENCH_LONGITUDE),
    Greek (GREEK_LATITUDE to GREEK_LONGITUDE),
    Indian (INDIAN_LATITUDE to INDIAN_LONGITUDE),
    Irish (IRISH_LATITUDE to IRISH_LONGITUDE),
    Italian (ITALIAN_LATITUDE to ITALIAN_LONGITUDE),
    Japanese (JAPANESE_LATITUDE to JAPANESE_LONGITUDE),
    Mexican (MEXICAN_LATITUDE to MEXICAN_LONGITUDE),
    Russian (RUSSIAN_LATITUDE to RUSSIAN_LONGITUDE),
    Spanish (SPANISH_LATITUDE to SPANISH_LONGITUDE),
    Turkish (TURKISH_LATITUDE to TURKISH_LONGITUDE),
    Vietnamese (VIETNAMESE_LATITUDE to VIETNAMESE_LONGITUDE),
    Australian (AUSTRALIAN_LATITUDE to AUSTRALIAN_LONGITUDE),
    Brazilian (BRAZILIAN_LATITUDE to BRAZILIAN_LONGITUDE),
    German (GERMAN_LATITUDE to GERMAN_LONGITUDE),
    Korean (KOREAN_LATITUDE to KOREAN_LONGITUDE),
    Swedish (SWEDISH_LATITUDE to SWEDISH_LONGITUDE),
    Swiss (SWISS_LATITUDE to SWISS_LONGITUDE),
    Thai (THAI_LATITUDE to THAI_LONGITUDE),
    Belgian (BELGIAN_LATITUDE to BELGIAN_LONGITUDE),
    Austrian (AUSTRIAN_LATITUDE to AUSTRIAN_LONGITUDE),
    Danish (DANISH_LATITUDE to DANISH_LONGITUDE),
    Portuguese (PORTUGUESE_LATITUDE to PORTUGUESE_LONGITUDE),
    Polish (POLISH_LATITUDE to POLISH_LONGITUDE),
    Hungarian (HUNGARIAN_LATITUDE to HUNGARIAN_LONGITUDE),
    Moroccan (MOROCCAN_LATITUDE to MOROCCAN_LONGITUDE),
    Tunisian (TUNISIAN_LATITUDE to TUNISIAN_LONGITUDE),
    Filipino (FILIPINO_LATITUDE to FILIPINO_LONGITUDE),
    Kenyan (KENYAN_LATITUDE to KENYAN_LONGITUDE),
    Malaysian (MALAYSIAN_LATITUDE to MALAYSIAN_LONGITUDE),
    Jamaican (JAMAICAN_LATITUDE to JAMAICAN_LONGITUDE),
    Unknown (UNKNOWN_LATITUDE to UNKNOWN_LONGITUDE)
}
